function obj = faster_rcnn_autonn_custom_fn(block, inputs, params)
% converter to autonn
  switch class(block)
    case 'dagnn.Reshape'
      obj = Layer.create(@vl_nnreshape, {inputs{1}, block.shape}) ;
    case 'dagnn.ProposalRPN'
      obj = Layer.create(@vl_nnproposalrpn, {inputs{1}, inputs{2}, ...
                          inputs{3}, 'featStride', block.featStride, ...
                          'scales', reshape(double(block.scales), 1, [])}, ...
                           'numInputDer', 0) ;
    case 'dagnn.ROIPooling'
      obj = Layer.create(@vl_nnroipool, {inputs{1}, inputs{2}, ...
                                  'subdivisions', block.subdivisions, ...
                                  'transform', block.transform}, ...
                                  'numInputDer', 0) ;
  end
